name: StoryJuicer
options:
  bundleIdPrefix: com.jakerains
  deploymentTarget:
    macOS: "26.0"
    iOS: "26.0"
  xcodeVersion: "26.0"
  minimumXcodeGenVersion: "2.40.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"

packages:
  MLXSwift:
    url: https://github.com/ml-explore/mlx-swift
    exactVersion: 0.30.6
  MLXSwiftLM:
    url: https://github.com/ml-explore/mlx-swift-lm
    exactVersion: 2.30.3
  SwiftTransformers:
    url: https://github.com/huggingface/swift-transformers
    exactVersion: 1.1.6
  SwiftHuggingFace:
    url: https://github.com/huggingface/swift-huggingface
    from: "0.5.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.8.1"

targets:
  StoryJuicer:
    type: application
    platform: macOS
    sources:
      - path: StoryJuicerApp.swift
      - path: Shared
      - path: macOS
      - path: Resources/Assets.xcassets
      - path: Resources/Diffusers
        buildPhase: resources
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jakerains.StoryJuicer
        PRODUCT_NAME: StoryJuicer
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.1.1"
        CURRENT_PROJECT_VERSION: "5"
        CODE_SIGN_ENTITLEMENTS: Resources/StoryJuicer.entitlements
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_FILE: Resources/StoryJuicer-Info.plist
        SWIFT_STRICT_CONCURRENCY: complete
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleURLTypes: >-
          <array><dict>
          <key>CFBundleURLName</key><string>com.jakerains.StoryJuicer.oauth</string>
          <key>CFBundleURLSchemes</key><array><string>storyjuicer</string></array>
          </dict></array>
    dependencies:
      - package: MLXSwift
        product: MLX
      - package: MLXSwiftLM
        product: MLXLLM
      - package: MLXSwiftLM
        product: MLXLMCommon
      - package: SwiftTransformers
        product: Hub
      - package: SwiftHuggingFace
        product: HuggingFace
      - package: Sparkle
    entitlements:
      path: Resources/StoryJuicer.entitlements

  StoryJuicer-iOS:
    type: application
    platform: iOS
    sources:
      - path: StoryJuicerApp.swift
      - path: Shared
      - path: iOS
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jakerains.StoryJuicer
        PRODUCT_NAME: StoryJuicer
        DEVELOPMENT_TEAM: 47347VQHQV
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: Resources/StoryJuicer-iOS.entitlements
        GENERATE_INFOPLIST_FILE: "YES"
        SWIFT_STRICT_CONCURRENCY: complete
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleURLTypes: >-
          <array><dict>
          <key>CFBundleURLName</key><string>com.jakerains.StoryJuicer.oauth</string>
          <key>CFBundleURLSchemes</key><array><string>storyjuicer</string></array>
          </dict></array>
    dependencies:
      - package: MLXSwift
        product: MLX
      - package: MLXSwiftLM
        product: MLXLLM
      - package: MLXSwiftLM
        product: MLXLMCommon
      - package: SwiftTransformers
        product: Hub
      - package: SwiftHuggingFace
        product: HuggingFace
    entitlements:
      path: Resources/StoryJuicer-iOS.entitlements
