name: StoryJuicer
options:
  bundleIdPrefix: com.jakerains
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "26.0"
  minimumXcodeGenVersion: "2.40.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"

targets:
  StoryJuicer:
    type: application
    platform: macOS
    sources:
      - path: StoryJuicerApp.swift
      - path: Shared
      - path: macOS
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jakerains.StoryJuicer
        PRODUCT_NAME: StoryJuicer
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: Resources/StoryJuicer.entitlements
        GENERATE_INFOPLIST_FILE: "YES"
        SWIFT_STRICT_CONCURRENCY: complete
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Resources/StoryJuicer.entitlements
